server:
  port: 9009
spring:
  application:
    name: tensquare_sms
  rabbitmq:
    host: 127.0.0.1
aliyun:
  sms:
    accessKeyId: XXXXXX
    accessKeySecret: XXXXXX
    template_code: XXXXXXX
    sign_name: XXXXXXX
